[pytest]
addopts = -ra
markers =
    unit: Unit test suite
    integration: Integration test suite (generic)
    dev_integration: Integration tests for the dev environment (LocalStack)
    prod_integration: Integration tests for the prod environment (AWS)
